### ISSUE TITLE
Revisi frontend

### ISSUE THREAD

**Issue by ovancop** [OtherProject/API#1]
Request dari Bapak,
1. Lebar banner = lebar teks
2. Tulisan pake tipe latto dan diperbesar
3. minta add video

**Comment by kartikadsiregar** [comment]
- [x] Lebar banner = lebar teks
- [x] Tulisan pake tipe latto dan diperbesar

**Comment by kartikadsiregar** [comment]
- [x] minta add video

**Comment by kartikadsiregar** [comment]
closed e76c1fd8ee839ff9a3bada9a066382fec08594c3
