### ISSUE TITLE
Tampilan Struktur Organisasi 

### ISSUE THREAD

**Issue by tieastie** [OtherProject/API#11]
Ta.. Bisa tolong buat tampilan statis untuk struktur organisasi 2013-2017?

tampilan sebagai berikut (statis).
nb : tanda panah ngewakilin level submenu. 
Struktur organisasi -> Dewan kehormatan
Struktur organisasi -> Dewan penasihat
Struktur organisasi -> Dewan pengurus -> Dewan pengurus umum (isinya ketua umum dsb)
Struktur organisasi -> Dewan pengurus -> Kabid a
Struktur organisasi -> Dewan pengurus -> Kabid b
Struktur organisasi -> Dewan pengurus -> Kabid ... n
Struktur organisasi -> Perwakilan -> Perwakilan Dalam Negeri 
Struktur organisasi -> Perwakilan -> Perwakilan Luar Negeri

**Comment by tieastie** [comment]
liat foto yang gua attach ya dit.. ada error
[asosiasi profesor indonesia 2015-02-17 20-28-00](https://cloud.githubusercontent.com/assets/9799454/6224055/f6297ae4-b6a7-11e4-8bfc-e1a2325f69ed.png)

**Comment by widiw** [comment]
klo itu dibikin 2 level gimana ke? dia mau ga? jadi pas dewan pengurus dia ngisi sekaligus 4.
