### ISSUE TITLE
Revisi Kepakaran

### ISSUE THREAD

**Issue by ovancop** [OtherProject/API#3]
1. Kalo copas cari web, maria db nya suka error
2. isi kepanjangan juga ngasih masalah di DB
3. tampilan kepakaran hilang
4. untuk registrasi belum ada validasi data input terutama untuk KTP
5. berita terbaru, tampilan depan belum singkron
6. Kliping kegiatan di home belum sesuai datanya

**Comment by ovancop** [comment]
Point 5 Done

**Comment by tieastie** [comment]
horeee~.. klo yang editornya gimana van?

2015-02-04 11:07 GMT+07:00 Ovan Pulu notifications@github.com:

> Point 5 Done
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/OtherProject/API/issues/3#issuecomment-72787471.

## 

Regards,

Astie Darmayantie

**Comment by ovancop** [comment]
lagi di test bu :)

**Comment by ovancop** [comment]
Point 1&2 Done [programmer testing :)]

**Comment by tieastie** [comment]
van.. tadi gue lagi isi artikel ko ada error parentid value ya?

2015-02-04 12:04 GMT+07:00 Ovan Pulu notifications@github.com:

> Point 1&2 Done [programmer testing :)]
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/OtherProject/API/issues/3#issuecomment-72791341.

## 

Regards,

Astie Darmayantie

**Comment by tieastie** [comment]
sudah bisya.. hehehehe itu tadi kenapa yak?

2015-02-04 12:18 GMT+07:00 astie darmayantie astie.darmayantie@gmail.com:

> van.. tadi gue lagi isi artikel ko ada error parentid value ya?
> 
> 2015-02-04 12:04 GMT+07:00 Ovan Pulu notifications@github.com:
> 
> > Point 1&2 Done [programmer testing :)]
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/OtherProject/API/issues/3#issuecomment-72791341.
> 
> ## 
> 
> Regards,
> 
> Astie Darmayantie

## 

Regards,

Astie Darmayantie

**Comment by tieastie** [comment]
Point 6. Kliping kegiatan di front-end belum dijahit hehehe

2015-02-04 12:21 GMT+07:00 astie darmayantie astie.darmayantie@gmail.com:

> sudah bisya.. hehehehe itu tadi kenapa yak?
> 
> 2015-02-04 12:18 GMT+07:00 astie darmayantie astie.darmayantie@gmail.com
> :
> 
> > van.. tadi gue lagi isi artikel ko ada error parentid value ya?
> > 
> > 2015-02-04 12:04 GMT+07:00 Ovan Pulu notifications@github.com:
> > 
> > > Point 1&2 Done [programmer testing :)]
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/OtherProject/API/issues/3#issuecomment-72791341.
> > 
> > ## 
> > 
> > Regards,
> > 
> > Astie Darmayantie
> 
> ## 
> 
> Regards,
> 
> Astie Darmayantie

## 

Regards,

Astie Darmayantie

**Comment by ovancop** [comment]
Point 6 Done

**Comment by tieastie** [comment]
maaci ovan... cemangat!

2015-02-04 19:16 GMT+07:00 Ovan Pulu notifications@github.com:

> Point 6 Done
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/OtherProject/API/issues/3#issuecomment-72845002.

## 

Regards,

Astie Darmayantie

**Comment by ovancop** [comment]
Point 3 Done [by er-joned]

**Comment by ovancop** [comment]
Point 4 mungkin maksudnya NIP/NIDN ya? [ Done ]

**Comment by tieastie** [comment]
engga kmrn gua input ktp ada abcdnya asal masih bisa masuk van... 

terus kl nidn/nip gua gatau format constrainnya coba di cek seinget gua si angka.. tp kl nidn agak susah kl pengen verifikasi karna databasenya di dikti 😂

Best,

Astie Darmayantie
envoyé de mon iPhone
