### ISSUE TITLE
Revisi Tampilan

### ISSUE THREAD

**Issue by tieastie** [OtherProject/API#4]
Dita  : 
1. Tampilan banner lebarnya belum sesuai text ( jangan2 belum commit? )
2. Tampilan thumbnail berita di home depan di force ukuran aja kali ya? -> foto ntar gue WA

**Comment by kartikadsiregar** [comment]
@tieastie ini udh gue revisi, tapi waktu itu emang belom diupload ke server. e76c1fd8ee839ff9a3bada9a066382fec08594c3
