### ISSUE TITLE
Tambah Agenda

### ISSUE THREAD

**Issue by tieastie** [OtherProject/API#9]
- Date picker klo di klik logonya (bukan text areanya) calendernya gak keluar.
- Belum ke jait dengan tampilan interfacenya

**Comment by widiw** [comment]
klo untuk datepicker yang di agenda ini pake datetimepicker supaya ada waktu nya.
Nah disini datetimepicker cuma bisa pilih satu antara icon atau field nya yang di click.

Barusan gw akalin bisa, tapi cuma untuk klik pertama, jadi masih ada problem. _info lebih lanjut tanya gw_

Nanti tinggal pilih aja mau klik di field nya, icon nya atau dua2nya tapi dengan sedikit problem.

pindah dulu ya asignee nya, gw ke gallery dulu.

**Comment by tieastie** [comment]
Oke.. yang gallery gimana nje? sampe skrg belum bisa soalnya.

Pada 11 Februari 2015 14.51, Fitri Nurjannah notifications@github.com
menulis:

> klo untuk datepicker yang di agenda ini pake datetimepicker supaya ada
> waktu nya.
> Nah disini datetimepicker cuma bisa pilih satu antara icon atau field nya
> yang di click.
> 
> Barusan gw akalin bisa, tapi cuma untuk klik pertama, jadi masih ada
> problem. _info lebih lanjut tanya gw_
> 
> Nanti tinggal pilih aja mau klik di field nya, icon nya atau dua2nya tapi
> dengan sedikit problem.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/OtherProject/API/issues/9#issuecomment-73844236.

## 

Regards,

Astie Darmayantie

**Comment by kartikadsiregar** [comment]
Tampilan agenda sudah dijahit. 9d2d89f5adf37428a6372f25bb361a0bb446c65e & f0b6a92964129ba8cba2326a60ddb2e95abd5c9e

**Comment by tieastie** [comment]
Ini ada issue tambahan : 
- Klo tanggal mulai event dan berakhirnya sama -> secara otomatis tanggal mulainya berubah jadi tanggal hari ini (begitu juga klo kita edit news). 
- Klo di calender di ganti bulan, tampilan list kegiatan gak berubah bulannya. tetep dibulan yang sama.

**Comment by widiw** [comment]
done
